var_comp = ('a', 'e', 'i', 'o', 'u')
print(var_comp)
print(var_comp[1])
print(var_comp[0:2])
print(var_comp[2:])
print(var_comp[-1])
print(var_comp[-5])
print(len(var_comp))
print(var_comp.count('a'))
