dadosjoao = list()
dadosmaria = list()
dadosantonio = list()
dadosjoao.append('Joao')
dadosjoao.append(25)
dadosmaria.append('Maria')
dadosmaria.append(39)
dadosantonio.append('Antonio')
dadosantonio.append(18)
print(dadosjoao)
print(dadosmaria)
print(dadosantonio)

pessoas = list()
pessoas.append(dadosjoao[:])
pessoas.append(dadosmaria[:])
pessoas.append(dadosantonio[:])
print(pessoas)

