frase = 'Curso em Video Python'
# print(frase[3])
# print(frase[13:])
# print(frase[:18:2])
# print(frase[3:17:3])
# print(frase.find('x'))
# print('Curso' in frase)
# print(frase.lower())
# print(frase.upper())
# frase1 = frase.upper()
# print(frase.capitalize())
# print(frase.title())
# print(frase)
# print(frase1)
# frase2 = frase.strip()
# print(frase2)
# (frase.upper().count('O'))
# print(frase.replace('em', 'do').upper())
# print(len(frase))
# print('Video' in frase)
# print(frase.find('Video'))
frase3 = frase.split()
print(frase.split())
print(frase3[3][3])
print(frase3)
print(frase)
print('-'.join(frase3))
